config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :users
  resources :courses,          only: [:create, :destroy]
  get 'users/new'

  root 'pages#home'

  get '/help', to: 'pages#help'
  get  '/courses',   to: 'pages#courses'
  get  '/programs', to: 'pages#programs'
  get  '/schools', to: 'pages#schools'
  get  '/dashboard', to: 'pages#dashboard'
  get  '/profile', to: 'pages#profile'
  get  '/account', to: 'pages#account'
  get  '/signout', to: 'pages#signout'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :courses, dependent: :destroy
  attr_accessor :remember_token


  #Regular expression for validating emails
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  #To save all emails in downcase
  before_save { self.email = email.downcase }

  #Validating name :
  validates :name,  presence: true, length: { maximum: 50 }

  #Validating email :
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  #Validating password
   validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  has_secure_password

    class << self

      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def new_token
        SecureRandom.urlsafe_base64
      end
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
   def authenticated?(remember_token)
     BCrypt::Password.new(remember_digest).is_password?(remember_token)
   end

   # Forgets a user.
   def forget
     update_attribute(:remember_digest, nil)
   end
   
    def feed
        Course.where("user_id = ?", id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
   private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   before_action :logged_in_user, only: [:create, :destroy]
   before_action :correct_user,   only: :destroy

  def create
    @course = current_user.courses.build(course_params)
    if @course.save
      flash[:success] = "Course created!"
      redirect_to root_url
    else

      @feed_items = []
      render 'pages/home'
    end
  end



    def destroy
      @course.destroy
      flash[:success] = "Course deleted"
      redirect_to request.referrer || root_url
    end

  private

    def course_params
      params.require(:course).permit(:content)
    end

    def correct_user
     @course = current_user.courses.find_by(id: params[:id])
     redirect_to root_url if @course.nil?
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    if logged_in?
      @course  = current_user.courses.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end


  def courses
  end

  def programs
  end

  def schools
  end

  def dashboard
  end

  def profile
  end

  def account
  end

  def signout
  end

  def help
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end



  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :logged_in_user, only: [:edit, :update]
before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @courses = @user.courses.paginate(page: params[:page])

  end

  def index
    @users = User.paginate(page: params[:page])
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
     @user = User.find(params[:id])
   end

   def update
     @user = User.find(params[:id])
     if @user.update_attributes(user_params)
       # Handle a successful update.
     else
       render 'edit'
     end
   end

   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end


  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end



  # PRIVATE !!

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

    # Returns the current logged-in user (if any).
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

  def logged_in?
    !current_user.nil?
  end

 def current_user?(user)
    user == current_user
  end


    # Forgets a persistent session.
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

    # Logs out the current user.
    def log_out
      forget(current_user)
      session.delete(:user_id)
      @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/courses/_course.html.erb
<li id="course-<%= course.id %>">
<% youtubeURL = course.content %>
<% youtubeURL[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/] %>
<% video_embed_id = $5 %>

  <%= link_to gravatar_for(course.user, size: 50), course.user %>
  <span class="user"><%= link_to course.user.name, course.user %></span>
 <span class="content"></span>
  <iframe title="Ouissal Project Player"  width="560" height="315"  src="http://www.youtube.com/embed/<%= video_embed_id %>" frameborder="0" allowfullscreen></iframe>
  <span class="timestamp">
    Posted <%= time_ago_in_words(course.created_at) %> ago.
        <% if current_user?(course.user) %>
      <%= link_to "delete", course, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
  
</li> 

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

<div class="content-footer">
</div>
 <footer id="myFooter">
     <div class="container">
         <div class="row">
             <div class="col-sm-3">
                 <h2 class="logo"><a href="#"><img src="<%= asset_path 'edx_logo.png' %>"></a></h2>
             </div>
             <div class="col-sm-2">
                 <h5>Get started</h5>
                 <ul>
                     <li><a href="#">Home</a></li>
                     <li><a href="#">Sign up</a></li>
                     <li><a href="#">Downloads</a></li>
                 </ul>
             </div>
             <div class="col-sm-2">
                 <h5>About us</h5>
                 <ul>
                     <li><a href="#">Company Information</a></li>
                     <li><a href="#">Contact us</a></li>
                     <li><a href="#">Reviews</a></li>
                 </ul>
             </div>
             <div class="col-sm-2">
                 <h5>Support</h5>
                 <ul>
                     <li><a href="#">FAQ</a></li>
                     <li><a href="#">Help desk</a></li>
                     <li><a href="#">Forums</a></li>
                 </ul>
             </div>
             <div class="col-sm-3">
                 <div class="social-networks">
                     <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                     <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                     <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                 </div>
                 <button type="button" class="btn btn-default">Contact us</button>
             </div>
         </div>
     </div>
     <div class="footer-copyright">
         <p>© 2016-2017 Rails Project </p>
     </div>
 </footer>
 <!--
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <a class="navbar-brand"  href="#" ><img id ="navbarLogo" src="<%= asset_path 'edx_logo.png' %>"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li class="dropdown">
          <a href="#"   class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Programs <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

        <li><a href="#">Schools and Partners</a></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
      <!--  <li><a href="#">Sign in</a></li>-->


        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <%= link_to "Register", signup_path, class: "btn btn-primary btn-lg" %>
        <% end %>








       <!-- <a class="btn btn-primary btn-lg" href="#" role="button"></a>-->

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= yield(:title) %> | MOOC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
  <!--  <div class="container">-->
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>

      <%= yield %>
      
   
      <%= render 'layouts/footer' %>

<!--    </div>-->
  </body>

</html>

app/views/pages/account.html.erb
<% provide(:title, "Account") %>
<h1>Sample App</h1>

app/views/pages/courses.html.erb
<% provide(:title, "Courses") %>
<h1>Sample App</h1>
=

app/views/pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<h1>Sample App</h1>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Sample App</h1>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="course_form">
        <%= render 'shared/course_form' %>
      </section>
    </aside>
        <div class="col-md-8">
      <h3>Course Feed</h3>
      <%= render 'shared/feed' %>
    </div>

  </div>
<% else %>

    <div class="jumbotron" id = "jumbImg" style="height: 400px;">
    <h1>Free Online Courses</h1>
    <div ></div>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Find courses</a></p>
    </div>

<% end %>

app/views/pages/profile.html.erb
<% provide(:title, "Profile") %>
<h1>Sample App</h1>

app/views/pages/programs.html.erb
<% provide(:title, "Programs") %>
<h1>Sample App</h1>

app/views/pages/schools.html.erb
<% provide(:title, "Schools") %>
<h1>Sample App</h1>

app/views/pages/signout.html.erb
<% provide(:title, "Signout") %>
<h1>Sample App</h1>

app/views/shared/_course_form.html.erb
<%= form_for(@course) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Enter the course's video link..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %> 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="courses">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %> 

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.courses.count, "course") %></span> 

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %> 

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<!--<%= @user.name %>, <%= @user.email %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>-->


<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="pagination col-md-8">
    <% if @user.courses.any? %>
      <h3>Courses (<%= @user.courses.count %>)</h3>
      <ol class="courses">
        <%= render @courses %>
      </ol>
      <%= will_paginate @courses %>
    <% end %>
  </div>
</div>